-------------------------------------------------------------------------------
connect to plant user admin using 1010;
-------------------------------------------------------------------------------

CREATE TABLE ILDAR.BOL ( 
	ID               TIMESTAMP       NOT NULL   WITH DEFAULT   PRIMARY KEY,
	N                SMALLINT                                             ,
	IDATE            DATE            NOT NULL                             ,
	SHIPPER          VARCHAR(200)                                         ,
	CONSIGNEE        VARCHAR(200)                                         ,
	NOTIFYADDRESS    VARCHAR(200)                                         ,
	SHIPOWNER        VARCHAR(200)                                         ,
	FLAG             VARCHAR(80)                                          ,
	VESSEL           VARCHAR(80)                                          ,
	PORTOFLOADING    VARCHAR(80)                                          ,
	PORTOFDISCHARGE  VARCHAR(80)                                          ,
	DISTINATION      VARCHAR(80)                                          ,
	FREIGHT1         VARCHAR(100)                                          ,
	FREIGHT2         VARCHAR(100)                                          ,
	MASTER           VARCHAR(40)                                          ,
	DESCRIPT         VARCHAR(400)                                         ,
	OPTIONS          VARCHAR(240)                                         ,
	BOLS             VARCHAR(240)                                         ,
	MNFSTBOT         VARCHAR(240)                                         ,
	NAME             VARCHAR(80)                                          ,
	MARKING          VARCHAR(40)                                          ,
	QUANTITY         VARCHAR(40)                                          ,
	WEIGHT           VARCHAR(20)                                          ,
	NAMERUS          VARCHAR(80)                                          ,
	NOTE             VARCHAR(20)                                          ,
	GROSS_WEIGHT     DECimal(8,3)                                         ,
	NETWEIGHT        DECimal(8,3)                                         ,  
	CONTRACT         VARCHAR(10)                                         );
--------------------------------------------------------------------------------
COMMENT ON ILDAR.BOL (
        ID                  IS        'дата записи'                           ,
        N                   IS        'номер документа'                       ,
        IDATE               IS        'дата документа'                        ,
        SHIPPER             IS        'отправитель'                           ,
        CONSIGNEE           IS        'получатель'                            ,
        NOTIFYADDRESS       IS        'извещать'                              ,
        SHIPOWNER           IS        'судовладелец'                          ,
        FLAG                IS        'флаг'                                  ,
        VESSEL              IS        'судно'                                 ,
        PORTOFLOADING       IS        'порт погрузки'                         ,
        PORTOFDISCHARGE     IS        'порт выгрузки'                         ,
        DISTINATION         IS        'пункт назначения'                      ,
        FREIGHT1            IS        'фрахт1'                                ,
        FREIGHT2            IS        'фрахт2'                                ,
        MASTER              IS        'капитан'                               ,
        DESCRIPT            IS        'описание'                              ,
        OPTIONS             IS        'дополнительные указания'               ,
        BOLS                IS        'список коносаментов'                   ,
        MNFSTBOT            IS        'примечание манифеста'                  ,
        NAME                IS        'имя товара'                            ,
        MARKING             IS        'маркировка'                            ,
        QUANTITY            IS        'число мест '                           ,
        WEIGHT              IS        'ед. измерения'                         ,
        NAMERUS             IS        'русское имя товара'                    ,
        NOTE                IS        'примечание'                            ,
        GROSS_WEIGHT        IS        'масса брутто'                          ,
        NETWEIGHT           IS        'масса нетто'                           ,  
        CONTRACT            IS        'контракт'                             );
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
