package uts.export.map;

//------------------------------------------------------------------------
// This code was generated by IBM VisualAge for Java Data Access Builder.
// WARNING: Modifications to this code will be lost on next code generation.
//------------------------------------------------------------------------



import java.lang.*;
import java.math.*;
import java.util.*;
import java.sql.*;
import com.ibm.ivj.eab.dab.*;
import java.io.Serializable;
import java.beans.*;

//----------------------------------------------------------------
//
// BolDataId - persistent object class data identifier
//
//----------------------------------------------------------------

public class BolDataId extends PODataId implements Cloneable, Serializable
{
 //----------------------------------------------------------------
 // BolDataId Attributes and methods
 //----------------------------------------------------------------

  /*--------------------------------------------------------------
	 BolDataId id access methods
	 This attribute is mapped to ID.
	--------------------------------------------------------------*/
   private Timestamp iId = null;

  boolean modified[] = { false };

 //----------------------------------------------------------------
 // Constructors
 //----------------------------------------------------------------
  public BolDataId() {}  
  public BolDataId( Timestamp aId ) {
	_setId(aId); 
  }  
   void _setId(Timestamp aId) {
	 if (_sendingAttributeEvents) {
	   Timestamp temp = iId; 
	   iId = aId; 
	   _changes.firePropertyChange("id",  temp, aId); 
	 } else {
	   iId = aId;
	 }
   }   
 //----------------------------------------------------------------
 // clone - returns a copy of the object
 //----------------------------------------------------------------
  public Object clone() {
	BolDataId obj = new BolDataId();

	obj.iId = iId; 

	return obj;
  }  
 //----------------------------------------------------------------
 // equals - compares itself with another object
 //----------------------------------------------------------------
  public boolean equals(Object anObject) {
	if ( !(anObject instanceof BolDataId) ) return false;
	BolDataId aDataId = (BolDataId)anObject;

	if ( iId != aDataId.iId ) {
	   if ( iId == null || aDataId.iId == null) return false;
	   else if ( !iId.equals( aDataId.iId ) ) return false;
	 } 

	return true;
  }  
  public Object[] getAttributes()
  {
	Object[] o = {getId()  };
	 return (o);
  }  
  public String[] getAttributeStrings()
  {
	String[] s = {String.valueOf(getId())  };
	 return (s);
  }  
   public Timestamp getId() { return iId; }   
   public boolean isIdNullable() { return false; }   
   public void setId(Timestamp aId) { 
	 Timestamp temp = iId; 
	 modified[0] = true;
	 iId = aId; 
	 setModified(true);
	 _changes.firePropertyChange("id",  temp, aId); 
   }   
  public void setModified(boolean enable) {
	if ( !enable ) {
	  for(int i=0; i < modified.length; i++) modified[i] = false;
	}
	super.setModified(enable);
  }  
  public String toString() { return toString("."); }  
 //----------------------------------------------------------------
 // Display methods
 //----------------------------------------------------------------
  public String toString(String aseparator) {
	return (String.valueOf(getId()));
  }  
}