package uts.export.map;

//---------------------------------------------------------------------------
// This code was generated by IBM VisualAge for Java Data Access Builder.
// WARNING: Modifications to this code will be lost on next code generation.
//---------------------------------------------------------------------------



import java.lang.*;
import java.math.*;
import java.util.*;
import java.sql.*;
import com.ibm.ivj.eab.dab.*;
import java.awt.*;

//-----------------------------------------------------------------------------------
// The following class(es) are used to _map a result set into a Bol
//-----------------------------------------------------------------------------------
class BolMap implements DAMap
{
  public void putResultSetInto(DataAccessObject obj, ResultSet rs, boolean saveStream) throws DAException, SQLException {
	Bol theObj = (Bol)obj;

	theObj._setId(rs.getTimestamp(1));
	if (rs.wasNull()) theObj._setId(null);
	theObj._setN(new Short(rs.getShort(2)));
	if (rs.wasNull()) theObj._setN(null);
	theObj._setIdate(rs.getDate(3));
	if (rs.wasNull()) theObj._setIdate(null);
	theObj._setShipper(rs.getString(4));
	if (rs.wasNull()) theObj._setShipper(null);
	theObj._setConsignee(rs.getString(5));
	if (rs.wasNull()) theObj._setConsignee(null);
	theObj._setNotifyaddress(rs.getString(6));
	if (rs.wasNull()) theObj._setNotifyaddress(null);
	theObj._setShipowner(rs.getString(7));
	if (rs.wasNull()) theObj._setShipowner(null);
	theObj._setFlag(rs.getString(8));
	if (rs.wasNull()) theObj._setFlag(null);
	theObj._setVessel(rs.getString(9));
	if (rs.wasNull()) theObj._setVessel(null);
	theObj._setPortofloading(rs.getString(10));
	if (rs.wasNull()) theObj._setPortofloading(null);
	theObj._setPortofdischarge(rs.getString(11));
	if (rs.wasNull()) theObj._setPortofdischarge(null);
	theObj._setDistination(rs.getString(12));
	if (rs.wasNull()) theObj._setDistination(null);
	theObj._setFreight1(rs.getString(13));
	if (rs.wasNull()) theObj._setFreight1(null);
	theObj._setFreight2(rs.getString(14));
	if (rs.wasNull()) theObj._setFreight2(null);
	theObj._setMaster(rs.getString(15));
	if (rs.wasNull()) theObj._setMaster(null);
	theObj._setDescript(rs.getString(16));
	if (rs.wasNull()) theObj._setDescript(null);
	theObj._setOptions(rs.getString(17));
	if (rs.wasNull()) theObj._setOptions(null);
	theObj._setBols(rs.getString(18));
	if (rs.wasNull()) theObj._setBols(null);
	theObj._setMnfstbot(rs.getString(19));
	if (rs.wasNull()) theObj._setMnfstbot(null);
	theObj._setName(rs.getString(20));
	if (rs.wasNull()) theObj._setName(null);
	theObj._setMarking(rs.getString(21));
	if (rs.wasNull()) theObj._setMarking(null);
	theObj._setQuantity(rs.getString(22));
	if (rs.wasNull()) theObj._setQuantity(null);
	theObj._setWeight(rs.getString(23));
	if (rs.wasNull()) theObj._setWeight(null);
	theObj._setNamerus(rs.getString(24));
	if (rs.wasNull()) theObj._setNamerus(null);
	theObj._setNote(rs.getString(25));
	if (rs.wasNull()) theObj._setNote(null);
	theObj._setGross_weight(new Double(rs.getDouble(26)));
	if (rs.wasNull()) theObj._setGross_weight(null);
	theObj._setNetweight(new Double(rs.getDouble(27)));
	if (rs.wasNull()) theObj._setNetweight(null);
	theObj._setContract(rs.getString(28));
	if (rs.wasNull()) theObj._setContract(null);

  }  
}