package uts.export.map;

//------------------------------------------------------------------------
// This code was generated by IBM VisualAge for Java Data Access Builder.
// WARNING: Modifications to this code will be lost on next code generation.
//------------------------------------------------------------------------



import java.lang.*;
import com.ibm.ivj.eab.dab.*;
import java.beans.*;

public class BolResultForm extends DataAccessResultForm
{
   private static String[] attributeLabels = {
			"дата записи",
			"N документа",
			"дата документа",
			"отправитель",
			"получатель",
			"извещать",
			"судовладелец",
			"флаг",
			"судно",
			"порт погрузки",
			"порт выгрузки",
			"пункт назначения",
			"фрахт1",
			"фрахт2",
			"капитан",
			"описание",
			"доп. указания",
			"список коносаментов",
			"прим. манифеста",
			"имя товара",
			"маркировка",
			"число мест",
			"ед. измерения",
			"рус. имя товара",
			"примечание",
			"масса брутто",
			"масса нетто",
			"контракт"  };
   public BolResultForm()
   {
	  this( new BolManager() );
   }   
   public BolResultForm(BolManager aManager)
   {
	  super(attributeLabels);
	  setManager(aManager);
   }   
   // only allow labels to be changed, not the number of columns
   public void setColumns( String[] labels )
   {
	  if ( labels.length != attributeLabels.length )
		 throw new IllegalArgumentException();
	  else
		 super.setColumns(labels);
   }   
}