package uts.export.map;

//------------------------------------------------------------------------
// This code was generated by IBM VisualAge for Java Data Access Builder.
// WARNING: Modifications to this code will be lost on next code generation.
//------------------------------------------------------------------------



import java.lang.*;
import java.math.*;
import java.util.*;
import java.beans.*;
import java.sql.*;
import com.ibm.ivj.eab.dab.*;
import java.io.Serializable;

//----------------------------------------------------------------
//
// Queryportofdischargebol - persistent object class
//
//---------------------------------------------------------------- 

/**
  * This class is mapped to QUERYportofdischargeBOL.
  */

public class Queryportofdischargebol extends PersistentObject implements Cloneable, Serializable
{

  private static DatastoreJDBC iQueryportofdischargebolDatastore;

  private static String _qualifier = "";

 //----------------------------------------------------------------
 // Queryportofdischargebol Attributes and methods
 //----------------------------------------------------------------

  /*--------------------------------------------------------------
	 Queryportofdischargebol portofdischarge access methods
	 This attribute is mapped to PORTOFDISCHARGE.
	--------------------------------------------------------------*/
   private String iPortofdischarge = null;

  boolean modified[] = { false };

  static DASQLGenerator generator = new DASQLGenerator("QUERYportofdischargeBOL",
													  null, 
													  new String[] {"PORTOFDISCHARGE"}, 
													  null, 
													  null );

 //----------------------------------------------------------------
 // Constructors
 //----------------------------------------------------------------
  public Queryportofdischargebol() {
	super(null); 
  }  
  public Queryportofdischargebol(DatastoreJDBC aDatastore) {
	super(aDatastore); 
  }  
 //----------------------------------------------------------------
 // Database access methods
 //----------------------------------------------------------------

  public void _executeAction( String _methodName, Object[] _params ) throws Exception { 

  }  
  protected POCompleteSupport _getPOCompleteSupport() { return _poSupport; }  
  protected static DatastoreJDBC _getStaticDatastore() {
	if (iQueryportofdischargebolDatastore != null) return iQueryportofdischargebolDatastore;
	else return DatastoreJDBC.getApplicationDatastore();
  }  
  protected void _setBusy(boolean flag) { super._setBusy(flag); }  
   void _setPortofdischarge(String aPortofdischarge) {
	 if (_sendingAttributeEvents) {
	   String temp = iPortofdischarge; 
	   iPortofdischarge = aPortofdischarge; 
	   _changes.firePropertyChange("portofdischarge",  temp, aPortofdischarge); 
	 } else {
	   iPortofdischarge = aPortofdischarge;
	 }
   }   
 //----------------------------------------------------------------
 // clone - returns a copy of the object
 //----------------------------------------------------------------
  public Object clone() {
 
	Queryportofdischargebol obj = new Queryportofdischargebol(getObjectsDatastore());

	obj.iPortofdischarge = iPortofdischarge; 

	return obj;
  }  
 //----------------------------------------------------------------
 // equals - compares itself with another object
 //----------------------------------------------------------------
  public boolean equals(Object anObject) {

	if ( !(anObject instanceof Queryportofdischargebol) ) return false;
	Queryportofdischargebol aQueryportofdischargebol = (Queryportofdischargebol)anObject;

	if ( iPortofdischarge != aQueryportofdischargebol.iPortofdischarge ) {
	   if ( iPortofdischarge == null || aQueryportofdischargebol.iPortofdischarge == null) return false;
	   else if ( !iPortofdischarge.equals( aQueryportofdischargebol.iPortofdischarge ) ) return false;
	 } 

	return true;
  }  
  public Object[] getAttributes() {
	Object[] o = {getPortofdischarge() };
	return (o);
  }  
  public String[] getAttributeStrings() {
	String[] s = {getPortofdischarge() };
	return (s);
  }  
  public DatastoreJDBC getCurrentDatastore() {
	if (getObjectsDatastore() != null) return getObjectsDatastore();
	else if (getDefaultDatastore() != null) return getDefaultDatastore();
	else return DatastoreJDBC.getApplicationDatastore();
  }  
 //----------------------------------------------------------------
 // Default Datastore
 //----------------------------------------------------------------
  public static DatastoreJDBC getDefaultDatastore() { return iQueryportofdischargebolDatastore; }  
   public String getPortofdischarge() { return iPortofdischarge; }   
  public static String getQualifier() { return _qualifier; }  
  public boolean hasDataId() { return false; }  
  public boolean isModified() {
	return super.isModified();
  }  
   public boolean isPortofdischargeNullable() { return true; }   
  public boolean isReadOnly() { return false; }  
  void setAllModified() {
	for(int i=0; i < modified.length; i++) modified[i] = true;
  }  
  public static void setDefaultDatastore(DatastoreJDBC aDatastore) { iQueryportofdischargebolDatastore = aDatastore; }  
  public void setModified(boolean enable) {
	if ( !enable ) { 
	  for(int i=0; i < modified.length; i++) modified[i] = false;
	}

	super.setModified(enable);
  }  
   public void setPortofdischarge(String aPortofdischarge) { 
	 String temp = iPortofdischarge; 
	 modified[0] = true;
	 iPortofdischarge = aPortofdischarge; 
	 setModified(true);
	 _changes.firePropertyChange("portofdischarge",  temp, aPortofdischarge); 
   }   
 //----------------------------------------------------------------
 // methods for setting the tablename dynamically
 //----------------------------------------------------------------
  public static void setQualifier(String qual) {
	if (qual == null) _qualifier = "";
	else if (qual.equals("")) _qualifier = qual;
	else if (!qual.endsWith(".")) _qualifier = qual + ".";
	else _qualifier = qual;
  }  
  public String toString() { return toString("."); }  
 //----------------------------------------------------------------
 // Display methods
 //----------------------------------------------------------------
  public String toString(String aSeparator)
  {
	return (getPortofdischarge());
  }  
}