package uts.export.map;

//------------------------------------------------------------------------
// This code was generated by IBM VisualAge for Java Data Access Builder.
// WARNING: Modifications to this code will be lost on next code generation.
//------------------------------------------------------------------------



import java.lang.*;
import java.math.*;
import java.util.*;
import java.beans.*;
import java.sql.*;
import com.ibm.ivj.eab.dab.*;
import java.io.Serializable;

//----------------------------------------------------------------
//
// Queryvesselbol - persistent object class
//
//---------------------------------------------------------------- 

/**
  * This class is mapped to QUERYvesselBOL.
  */

public class Queryvesselbol extends PersistentObject implements Cloneable, Serializable
{

  private static DatastoreJDBC iQueryvesselbolDatastore;

  private static String _qualifier = "";

 //----------------------------------------------------------------
 // Queryvesselbol Attributes and methods
 //----------------------------------------------------------------

  /*--------------------------------------------------------------
	 Queryvesselbol vessel access methods
	 This attribute is mapped to VESSEL.
	--------------------------------------------------------------*/
   private String iVessel = null;

  boolean modified[] = { false };

  static DASQLGenerator generator = new DASQLGenerator("QUERYvesselBOL",
													  null, 
													  new String[] {"VESSEL"}, 
													  null, 
													  null );

 //----------------------------------------------------------------
 // Constructors
 //----------------------------------------------------------------
  public Queryvesselbol() {
	super(null); 
  }  
  public Queryvesselbol(DatastoreJDBC aDatastore) {
	super(aDatastore); 
  }  
 //----------------------------------------------------------------
 // Database access methods
 //----------------------------------------------------------------

  public void _executeAction( String _methodName, Object[] _params ) throws Exception { 

  }  
  protected POCompleteSupport _getPOCompleteSupport() { return _poSupport; }  
  protected static DatastoreJDBC _getStaticDatastore() {
	if (iQueryvesselbolDatastore != null) return iQueryvesselbolDatastore;
	else return DatastoreJDBC.getApplicationDatastore();
  }  
  protected void _setBusy(boolean flag) { super._setBusy(flag); }  
   void _setVessel(String aVessel) {
	 if (_sendingAttributeEvents) {
	   String temp = iVessel; 
	   iVessel = aVessel; 
	   _changes.firePropertyChange("vessel",  temp, aVessel); 
	 } else {
	   iVessel = aVessel;
	 }
   }   
 //----------------------------------------------------------------
 // clone - returns a copy of the object
 //----------------------------------------------------------------
  public Object clone() {
 
	Queryvesselbol obj = new Queryvesselbol(getObjectsDatastore());

	obj.iVessel = iVessel; 

	return obj;
  }  
 //----------------------------------------------------------------
 // equals - compares itself with another object
 //----------------------------------------------------------------
  public boolean equals(Object anObject) {

	if ( !(anObject instanceof Queryvesselbol) ) return false;
	Queryvesselbol aQueryvesselbol = (Queryvesselbol)anObject;

	if ( iVessel != aQueryvesselbol.iVessel ) {
	   if ( iVessel == null || aQueryvesselbol.iVessel == null) return false;
	   else if ( !iVessel.equals( aQueryvesselbol.iVessel ) ) return false;
	 } 

	return true;
  }  
  public Object[] getAttributes() {
	Object[] o = {getVessel() };
	return (o);
  }  
  public String[] getAttributeStrings() {
	String[] s = {getVessel() };
	return (s);
  }  
  public DatastoreJDBC getCurrentDatastore() {
	if (getObjectsDatastore() != null) return getObjectsDatastore();
	else if (getDefaultDatastore() != null) return getDefaultDatastore();
	else return DatastoreJDBC.getApplicationDatastore();
  }  
 //----------------------------------------------------------------
 // Default Datastore
 //----------------------------------------------------------------
  public static DatastoreJDBC getDefaultDatastore() { return iQueryvesselbolDatastore; }  
  public static String getQualifier() { return _qualifier; }  
   public String getVessel() { return iVessel; }   
  public boolean hasDataId() { return false; }  
  public boolean isModified() {
	return super.isModified();
  }  
  public boolean isReadOnly() { return false; }  
   public boolean isVesselNullable() { return true; }   
  void setAllModified() {
	for(int i=0; i < modified.length; i++) modified[i] = true;
  }  
  public static void setDefaultDatastore(DatastoreJDBC aDatastore) { iQueryvesselbolDatastore = aDatastore; }  
  public void setModified(boolean enable) {
	if ( !enable ) { 
	  for(int i=0; i < modified.length; i++) modified[i] = false;
	}

	super.setModified(enable);
  }  
 //----------------------------------------------------------------
 // methods for setting the tablename dynamically
 //----------------------------------------------------------------
  public static void setQualifier(String qual) {
	if (qual == null) _qualifier = "";
	else if (qual.equals("")) _qualifier = qual;
	else if (!qual.endsWith(".")) _qualifier = qual + ".";
	else _qualifier = qual;
  }  
   public void setVessel(String aVessel) { 
	 String temp = iVessel; 
	 modified[0] = true;
	 iVessel = aVessel; 
	 setModified(true);
	 _changes.firePropertyChange("vessel",  temp, aVessel); 
   }   
  public String toString() { return toString("."); }  
 //----------------------------------------------------------------
 // Display methods
 //----------------------------------------------------------------
  public String toString(String aSeparator)
  {
	return (getVessel());
  }  
}