package uts.export.map;

//------------------------------------------------------------------------
// This code was generated by IBM VisualAge for Java Data Access Builder.
// WARNING: Modifications to this code will be lost on next code generation.
//------------------------------------------------------------------------



import java.lang.*;
import java.math.*;
import java.util.*;
import java.beans.*;
import java.sql.*;
import com.ibm.ivj.eab.dab.*;
import java.io.Serializable;

//----------------------------------------------------------------
//
// Queryfreightbol - persistent object class
//
//---------------------------------------------------------------- 

/**
  * This class is mapped to QUERYfreightBOL.
  */

public class Queryfreightbol extends PersistentObject implements Cloneable, Serializable
{

  private static DatastoreJDBC iQueryfreightbolDatastore;

  private static String _qualifier = "";

 //----------------------------------------------------------------
 // Queryfreightbol Attributes and methods
 //----------------------------------------------------------------

  /*--------------------------------------------------------------
	 Queryfreightbol result1 access methods
	 This attribute is mapped to result1.
	--------------------------------------------------------------*/
   private String iResult1 = null;

  boolean modified[] = { false };

  static DASQLGenerator generator = new DASQLGenerator("QUERYfreightBOL",
													  null, 
													  new String[] {"result1"}, 
													  null, 
													  null );

 //----------------------------------------------------------------
 // Constructors
 //----------------------------------------------------------------
  public Queryfreightbol() {
	super(null); 
  }  
  public Queryfreightbol(DatastoreJDBC aDatastore) {
	super(aDatastore); 
  }  
 //----------------------------------------------------------------
 // Database access methods
 //----------------------------------------------------------------

  public void _executeAction( String _methodName, Object[] _params ) throws Exception { 

  }  
  protected POCompleteSupport _getPOCompleteSupport() { return _poSupport; }  
  protected static DatastoreJDBC _getStaticDatastore() {
	if (iQueryfreightbolDatastore != null) return iQueryfreightbolDatastore;
	else return DatastoreJDBC.getApplicationDatastore();
  }  
  protected void _setBusy(boolean flag) { super._setBusy(flag); }  
   void _setResult1(String aResult1) {
	 if (_sendingAttributeEvents) {
	   String temp = iResult1; 
	   iResult1 = aResult1; 
	   _changes.firePropertyChange("result1",  temp, aResult1); 
	 } else {
	   iResult1 = aResult1;
	 }
   }   
 //----------------------------------------------------------------
 // clone - returns a copy of the object
 //----------------------------------------------------------------
  public Object clone() {
 
	Queryfreightbol obj = new Queryfreightbol(getObjectsDatastore());

	obj.iResult1 = iResult1; 

	return obj;
  }  
 //----------------------------------------------------------------
 // equals - compares itself with another object
 //----------------------------------------------------------------
  public boolean equals(Object anObject) {

	if ( !(anObject instanceof Queryfreightbol) ) return false;
	Queryfreightbol aQueryfreightbol = (Queryfreightbol)anObject;

	if ( iResult1 != aQueryfreightbol.iResult1 ) {
	   if ( iResult1 == null || aQueryfreightbol.iResult1 == null) return false;
	   else if ( !iResult1.equals( aQueryfreightbol.iResult1 ) ) return false;
	 } 

	return true;
  }  
  public Object[] getAttributes() {
	Object[] o = {getResult1() };
	return (o);
  }  
  public String[] getAttributeStrings() {
	String[] s = {getResult1() };
	return (s);
  }  
  public DatastoreJDBC getCurrentDatastore() {
	if (getObjectsDatastore() != null) return getObjectsDatastore();
	else if (getDefaultDatastore() != null) return getDefaultDatastore();
	else return DatastoreJDBC.getApplicationDatastore();
  }  
 //----------------------------------------------------------------
 // Default Datastore
 //----------------------------------------------------------------
  public static DatastoreJDBC getDefaultDatastore() { return iQueryfreightbolDatastore; }  
  public static String getQualifier() { return _qualifier; }  
   public String getResult1() { return iResult1; }   
  public boolean hasDataId() { return false; }  
  public boolean isModified() {
	return super.isModified();
  }  
  public boolean isReadOnly() { return false; }  
   public boolean isResult1Nullable() { return true; }   
  void setAllModified() {
	for(int i=0; i < modified.length; i++) modified[i] = true;
  }  
  public static void setDefaultDatastore(DatastoreJDBC aDatastore) { iQueryfreightbolDatastore = aDatastore; }  
  public void setModified(boolean enable) {
	if ( !enable ) { 
	  for(int i=0; i < modified.length; i++) modified[i] = false;
	}

	super.setModified(enable);
  }  
 //----------------------------------------------------------------
 // methods for setting the tablename dynamically
 //----------------------------------------------------------------
  public static void setQualifier(String qual) {
	if (qual == null) _qualifier = "";
	else if (qual.equals("")) _qualifier = qual;
	else if (!qual.endsWith(".")) _qualifier = qual + ".";
	else _qualifier = qual;
  }  
   public void setResult1(String aResult1) { 
	 String temp = iResult1; 
	 modified[0] = true;
	 iResult1 = aResult1; 
	 setModified(true);
	 _changes.firePropertyChange("result1",  temp, aResult1); 
   }   
  public String toString() { return toString("."); }  
 //----------------------------------------------------------------
 // Display methods
 //----------------------------------------------------------------
  public String toString(String aSeparator)
  {
	return (getResult1());
  }  
}